### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Killzero010** [RedDuckss/csms#2]
i generated the account.dat (im not sure where to put it though so i just putted it in the online files i got earlier that didnt contain the account.dat) and i also copy pasted all the certs in the correct places (scerts not the ccerts) but now my SMM is crashing after the intro screen (CEMU) plz help me fix this

**Comment by mrjvs** [comment]
Account.dat needs to be linked with the console where you got the otp and seeprom. You cannot use just any account.
Also, account.dat does have a specific folder structure for cemu

**Comment by jonbarrow** [comment]
this repo and project is deprecated. Development of custom server has moved to [Pretendo](https://github.com/PretendoNetwork/Pretendo)
