### ISSUE TITLE
tutorial plz

### ISSUE THREAD

**Issue by Nyges** [RedDuckss/csms#3]
HOW DO İ USE DİS 
THERE İS NOTİNG ON THE PROJECTS SECTİON

**Comment by EpicUsername12** [comment]
i think it have something to do with iosuhax but this Hykem fucker won't release it, back to 3ds i gueess :(
maybe try installing python 1.6, might work :D

**Comment by jonbarrow** [comment]
This repo is no longer maintained and only serves as a basic reference/wiki for some of the higher-level parts of the SMM REST API. There is no server here. All work on custom servers has been moved to the [PretendoNetwork](https://github.com/PretendoNetwork) project, which is currently _not_ ready for public use.
